<a href="https://colab.research.google.com/github/jiseon0516/pdm19/blob/main/numpy/numpy_2_array2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## concatenate()를 이용한 배열 결합 - 2개의 배열 가로,세로 합치기
> [numpy 배열 합치기, concatenate 함수](https://m.blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221490583222&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

In [1]:
import numpy as np

In [2]:
ar1 = np.array(range(1,5)).reshape(2,2) #np.array(range(1,5)).reshape(2,-1)
ar1

array([[1, 2],
       [3, 4]])

In [3]:
ar1.shape

(2, 2)

In [6]:
np.array(range(5,11)) #1차원 array

array([ 5,  6,  7,  8,  9, 10])

In [4]:
ar2 = np.array(range(5,11)).reshape(2,3)  # np.array(range(5,11)).reshape(-1,3)
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
ar2.shape  # 2 X 3 array

(2, 3)

In [9]:
print(ar1)
print(ar2)
ar1, ar2

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


(array([[1, 2],
        [3, 4]]), array([[ 5,  6,  7],
        [ 8,  9, 10]]))

---

## concatenate()를 이용한 배열 합치기


- concatenate(array1, array2, axis = 0)
- concatenate(array1, array2, axis = 1)
- concatenate(array1, array2, axis = None)

In [10]:
np.concatenate((ar1,ar1), axis=0) #합치려고 하는 배열 튜플로 묶기, 행 단위로(세로로 확장)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [11]:
np.concatenate((ar1,ar1,ar1), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [12]:
np.concatenate((ar1,ar1), axis=1) #가로로 확장

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [13]:
np.concatenate((ar1,ar1), axis=None) #모든 항목 1차원으로 확장

array([1, 2, 3, 4, 1, 2, 3, 4])

### ar2에 대하여도 배열합치기를 해보시오.

In [14]:
ar2 #2x3 구조

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [18]:
# Your code here!
print(np.concatenate((ar2,ar2), axis=0))
print(np.concatenate((ar2,ar2), axis=1))
print(np.concatenate((ar2,ar2), axis=None))

[[ 5  6  7]
 [ 8  9 10]
 [ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7  5  6  7]
 [ 8  9 10  8  9 10]]
[ 5  6  7  8  9 10  5  6  7  8  9 10]


### Error in concatenation

In [19]:
np.concatenate((ar1,ar2), axis=0)

#ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3(열의 개수 불일치)

ValueError: ignored

> ar1의 열의 갯수 == ar2의 열의 갯수

In [20]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [21]:
ar2.T.shape

(3, 2)

In [22]:
np.concatenate((ar1,ar2.T), axis=0) #열의 개수 2개로 일치

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### concatenate(array1, array2, axis = 1)

In [23]:
np.concatenate((ar1,ar2), axis=1) #행의 개수 2로 일치

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])



---



---



## [복습] numpy 배열 연산: broadcasting
> [파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자](https://blog.naver.com/qbxlvnf11/221509303462)

In [25]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b   # elementwise multiplication
# [출처] 파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자


array([2., 4., 6.])

In [26]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0 #스칼라 -> 차원x, 벡터구조로 변경// 1행 3열로 확장
a * b   # broadcasted multiplication


array([2., 4., 6.])

> 차원이 다른 두 개의 피연산자를 산술 연산할 때는 원래 연산이 불가능합니다.
하지만, 연산이 가능하도록 배열 b가 브로드캐스팅이 되어 numpy array ([2.0, 2.0, 2.0])으로 확장됩니다.

### 2차원 broadcasting

In [29]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]]) #4행 3열 - 2차원배열

b = np.array([1.0, 2.0, 3.0]) #열 개수 동일 -> 행 반복해서 일치시킴

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [30]:
(a+b).shape

(4, 3)

In [34]:
from numpy import array, newaxis
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0]) 
#a,b 열,행벡터 구분하기 - 다시
# c=a+b #ValueError: operands could not be broadcast together with shapes (4,) (3,) =>
c = a[:,newaxis] + b  #a[:,newaxis]: 열벡터로 변경
c

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [33]:
c.shape

(4, 3)

## numpy statistics
> [numpy: 기술 통계](https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html)
- min(), max()
- mean(), median(), var(), std()

In [36]:
# a = np.array(list(range(1,10)))
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# np.min, np.max
a.min(), a.max() #a: numpy 객체 변수

(1, 9)

In [39]:
# array.min(), array.max()
np.min(a), np.max(a) #min, max함수에 a를 매개별수로

(1, 9)

In [47]:
# mean()
a.mean(), np.mean(a) #정상적으로 작동

(5.0, 5.0)

In [45]:
# median()
np.median(a)
# print(a.median()) #AttributeError: 'numpy.ndarray' object has no attribute 'median'

5.0

In [48]:
# var(), std()
a.var(), a.std()

(6.666666666666667, 2.581988897471611)

In [49]:
np.var(a), np.std(a)

(6.666666666666667, 2.581988897471611)

## 2차원 배열의 기술 통계
- axis = 0 - 행
- axis = 1 - 열
- 결과 1차원 배열로

In [50]:
d2arr = np.arange(1,10).reshape(-1,3)
d2arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
d2arr.max()

9

In [52]:
d2arr.max(axis=0) #1,2,3번째 행 중에 큰 것(각각의 행에서 계산)

array([7, 8, 9])

In [53]:
d2arr.max(axis=1)

array([3, 6, 9])

In [57]:
print(d2arr.min(axis=None))
print(d2arr.min(axis=0))
print(d2arr.min(axis=1))

1
[1 2 3]
[1 4 7]


In [61]:
import numpy as np
d1arr = np.array([[1,2,3],[0,5,6],[7,8,9]])
d1arr
d1arr.max() # 다시 해보기

9

## [DIY: 도전과제]
- axis = None, 1, 2 에 따른 평균을 구하시오.

In [58]:
# Your code here!
print(d2arr.mean(axis=0))
print(d2arr.mean(axis=1))
print(d2arr.mean(axis=None))

[4. 5. 6.]
[2. 5. 8.]
5.0
