<a href="https://colab.research.google.com/github/jiseon0516/pdm19/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray #numpy모듈에서 asarray함수 사용
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data) #2차원리스트를 asarray함수 이용해 numpy배열로 변환// 주석처리하면 오류
# summarize the array content
print(data) #2차원 리스트
# summarize the array shape
print(data.shape) #2행 3열

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]] #리스트
# data.shape # Error!
# convert to a numpy array
data = asarray(data) #asarray: 데이터프레임 변경/데이터 구조, 성질 바꿈// numpy배열
# step through rows
#for row in range(data.shape[]):
#	print(data[])
for row in range(data.shape[0]): #data.shape[0]:2행
	print(data[row]) #row=0,1

[1 2 3]
[4 5 6]


In [ ]:
data.shape, data.shape[0], data.shape[1]

((2, 3), 2, 3)

In [ ]:
data.shape[0], data.shape[1]

(2, 3)

## Print columns

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]): #data.shape[1]:3열
	print(data[:,col]) #col=0,1,2

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise. #모든 항목
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None) #배열의 모든 항목의 합 #axis=None: 모든 항목 - default 값이므로 없어도 가능
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum(axis=1)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

In [ ]:
#asarray 이용

In [20]:
import numpy as np
from numpy import asarray
test1 = [[[0,1],[3,4]],
         [[9,10],[12,13]],
         [[18,19],[21,22]]]
test1
test = asarray(test1)
print(test)
result = test.sum(axis=0)
result1 = test.sum(axis=1)
result2 = test.sum(axis=2)
result3 = test.sum(axis=(0,1))
result4 = test.sum(axis=(1,2))
result5 = test.sum(axis=(0,2))

print(result)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(test.ndim)

[[[ 0  1]
  [ 3  4]]

 [[ 9 10]
  [12 13]]

 [[18 19]
  [21 22]]]
[[27 30]
 [36 39]]
[[ 3  5]
 [21 23]
 [39 41]]
[[ 1  7]
 [19 25]
 [37 43]]
[63 69]
[ 8 44 80]
[57 75]
3
